os: linux
language: node_js
node_js:
  - stable
  - lts/*

cache:
  directories:
    - node_modules

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      script: 
        - yarn test
      after_success: 
        - bash <(curl -s https://codecov.io/bash)
        - yarn semantic-release
