language: node_js

node_js:
  - lts/*

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        cleanup: false
        script:
          - npx semantic-release
    - stage: after-success
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      script: yarn report-coverage
      