os: linux
language: node_js
node_js:
  - stable
  - lts/*

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      script: npx semantic-release
      after_success: bash <(curl -s https://codecov.io/bash)

      